# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('from_email', models.EmailField(blank=True, max_length=80)),
                ('your_message', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
