# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181120_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='your_email',
        ),
    ]
