# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181022_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='your_message',
        ),
    ]
