# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181022_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
