# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address2',
        ),
    ]
