# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
