# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20181209_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='date',
            field=models.DateField(default='2017-12-09'),
        ),
    ]
