# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20181206_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='date',
            field=models.DateField(default='date.today()'),
        ),
    ]
