# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('★★★★★', '5 Stars'), ('★★★★', '4 Stars'), ('★★★', '3 Stars'), ('★★', '2 Stars'), ('★', '1 Star')], default='five_stars', max_length=50),
        ),
    ]
