# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
