# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181206_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], default='A4', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='', max_length=254),
        ),
    ]
